"""Layer 5: Skeleton (Predicate-Argument / PropBank-style event structure).

Re-exports the full public API and internal rule functions for backward compatibility.
"""

from __future__ import annotations

from ..case import CaseRow
from ..dep import DepRow, index as dep_index
from ..morph import MorphRow
from ..np import NPSpan
from .derive import (
    ARG_DEPRELS,
    CLAUSE_HEAD_DEPRELS,
    _ADJECTIVE_COMPLEMENT_DEPRELS,
    _ADNOMINAL_DEPRELS,
    _AUX_DEPRELS,
    _CONJ_WALK_LIMIT,
    _DIRECT_ROLE_MAP,
    _ELIDED_COPULA_DEPRELS,
    _FLOATING_QUANTIFIERS,
    _NOMINAL_SLOT_DEPRELS,
    _QUANTIFIER_POS,
    _SUBJ_DEPRELS,
    _accept_control_subjects,
    _adverb_cluster_head,
    _aux_head,
    _case_supports_role,
    _collapse_coordination,
    _conj_shared_argument,
    _conjunct_named_by_phrase_head,
    _coordination_head,
    _distinctly_marked_conjunct,
    _donor_predicate_disagrees,
    _finite_head_of,
    _floating_quantifier_of,
    _inherited_subject,
    _merge_adverb_cluster_citations,
    _merge_auxiliary_citations,
    _merge_floating_quantifier_citations,
    _merge_np_head_citations,
    _nested_in_named_phrase,
    _np_head_equivalent,
    _prep_lemma,
    _prep_stack_nominal,
    derive_unit,
    is_verb_pos,
)
from .io import (
    _TSV_HEADER,
    _alpha_tokens,
    _artifact_path,
    _iter_np,
    _parse_int,
    _words_match,
    antecedent,
    arg_np,
    artifact_path,
    children_index,
    has_skel,
    load_skel,
    morph_index,
    np_head_index,
    pro_drop_features,
    resolve_chunk,
    tuples_canto,
    write_skel,
)
from .models import (
    _COMPARATIVE_LEMMAS,
    _COMPARATIVE_PARTICLES,
    _LOCATIVE_RELATIVE_LEMMAS,
    _PREP_LEMMA_NORM,
    _REL_PRONOUN_WORDS,
    _RELATIVE_PRONOUNS,
    _RELATIVIZERS,
    _ROLE_CANON,
    _ROLE_RANK,
    OBL_RE,
    ROLES,
    SKEL_DIR,
    GrammarContext,
    ItalianLanguagePack,
    LanguagePack,
    Repair,
    SkelArg,
    SkelRow,
    SkelTuple,
    Violation,
    _canonicalize_role,
    _normalize_prep_lemma,
    _role_rank,
    _role_valid,
    _row_sort_key,
    canon_header,
)
from .registry import (
    RULES,
    Rule,
    RuleRegistry,
    rule_active,
)
from .repairs import (
    _case_child_lemmas,
    _find_repairs,
    _prep_stack_label,
    _safe_role_repair,
    _stacked_prep_lemmas,
)
from .rules import (
    _COMPLEMENT_ROLES,
    _accusative_and_infinitive,
    _adverbial_oblique,
    _apply_subj_authority,
    _bare_pronoun_position,
    _case_corroborated_role,
    _case_corroborated_swap,
    _case_marked_object,
    _clausal_complement_flavor,
    _clausal_object,
    _classify_divergence,
    _co_present_preposition,
    _comparative_come_adjunct,
    _comparative_come_complement,
    _conjunction_oblique,
    _depictive_attr_omitted,
    _depictive_bare_oblique,
    _depictive_bare_oblique_omitted,
    _displaced_subject_pro_drop,
    _drop_nmod_obliques,
    _fused_clitic_dual_role,
    _gapped_clause_read_as_predicate,
    _gapped_coordinate_oblique,
    _gapped_first_term_argument,
    _gapped_second_term_argument,
    _hosts_child,
    _inverted_copula_complement,
    _is_nominal_pos,
    _marked_adverbial_clause,
    _marked_complement_clause,
    _marker_of_derived_clause,
    _marker_slot_argument,
    _nmod_complement_of_predicate,
    _oblique_lemma_refinement,
    _predicative_advmod,
    _predicative_complement,
    _promoted_conjunct_argument,
    _stranded_on_underived_complement,
    _subj_arg,
    _subtree,
    _undecided_subject_slot,
    _wh_word_of_derived_clause,
)
from .validate import (
    _dual_role_violations,
    validate_unit,
)

__all__ = [
    "SkelRow",
    "SkelArg",
    "SkelTuple",
    "Repair",
    "Violation",
    "LanguagePack",
    "ItalianLanguagePack",
    "GrammarContext",
    "canon_header",
    "SKEL_DIR",
    "ROLES",
    "OBL_RE",
    "Rule",
    "RuleRegistry",
    "RULES",
    "rule_active",
    "is_verb_pos",
    "CLAUSE_HEAD_DEPRELS",
    "ARG_DEPRELS",
    "derive_unit",
    "validate_unit",
    "resolve_chunk",
    "np_head_index",
    "morph_index",
    "arg_np",
    "antecedent",
    "children_index",
    "pro_drop_features",
    "write_skel",
    "has_skel",
    "load_skel",
    "tuples_canto",
    "artifact_path",
]
